[template]
cargo_generate_version = ">=0.10.0"
ignore = [ "README.md", ".gitignore", ".vscode/cargo-generate-template.code-workspace" ]
# include = [ "..." ]
# exclude = [ "..." ]

[hooks]
pre = [ "pre-setup.rhai" ]
post = [ "post-setup.rhai" ]
